version: '3.2'
services:
  database:
    container_name: database
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_PASSWORD=r00t
      - POSTGRES_USERNAME=postgres
    ports:
      - "5432:5432"
  core:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=r00t
      - POSTGRES_USERNAME=postgres
    depends_on:
      - database
